### ISSUE TITLE
연락처 관리 앱 [STEP 1] Harry, Hoi

### ISSUE THREAD

**Issue by happykwon** [hemil0102/ios-contact-manager-ui#1]
## Feature  Issue
연락처 관리 앱 STEP1 모델링 및  테이블뷰 초기 구현 

## Todo
- [x] MVC 구조 적용 
- [x] 연락처 모델 구현 - 구조체
- [x] TableView 구현
- [x] 연락처 보기 기능 구현
- [x] 연락처 추가 기능 구현
- [x] 연락처 삭제 기능 구현
- [x] 연락처 변경 기능 구현
