### ISSUE TITLE
연락처 관리 앱 [STEP 2] Harry, Hoi

### ISSUE THREAD

**Issue by happykwon** [hemil0102/ios-contact-manager-ui#2]
## Feature  Issue
연락처 관리 앱 STEP2 연락처 추가 화면 구현 

## Todo
- [x] UML 작성 
- [x] 연락처 추가 화면 구현 (텍스트필드)
- [x] 연락처 추가 텍스트필드에 맞는 키보드 구현
- [x] 연락처 추가 시 Alert 구현 
- [x] 연락처 추가 시 연락처리스트 화면에 데이터 저장 구현
