### ISSUE TITLE
연락처 관리 앱 [STEP 3] Harry, Hoi

### ISSUE THREAD

**Issue by hemil0102** [hemil0102/ios-contact-manager-ui#3]
## Feature Issue

연락처 관리 앱 STEP3 연락처 삭제 및 기타 옵션 구현

## Todo

- [x] 연락처 삭제 기능 구현
- [x] 검색 기능 구현 (옵션)
- [ ] Dynamic Range 구현 (옵선)
- [ ] 커스텀 셀 구현 (옵션)

## 보너스
- [ ] 해외 전화번호 구현 
- [ ] 수정 화면 구현
